language: node_js
node_js:
  - "6.1.0"
services:
  - docker
before_script:
  - npm install -g grunt-cli
after_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
notifications:
  webhooks:
    urls:
      - http://webhooks.laterooms.com/travis-ci
    on_start: always
