language: node_js
node_js:
  - "6.2.2"
services:
  - docker
env:
  global:
    - DOCKER_VERSION=1.10.1-0~trusty
before_install:
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
before_script:
  - npm install -g grunt-cli
after_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t tlrg/graphite-es-bridge:${TRAVIS_BUILD_NUMBER} -t tlrg/graphite-es-bridge:latest  .
  - docker push tlrg/graphite-es-bridge:${TRAVIS_BUILD_NUMBER}
  - docker push tlrg/graphite-es-bridge:latest
notifications:
  webhooks:
    urls:
      - http://webhooks.laterooms.com/travis-ci
    on_start: always
